##############################
# Netlify configuration file #
##############################

[build]
  command = "npm run build"  # Vite build
  publish = "/frontend/dist"  

[[redirects]]
  from = "/*"
  to = "/frontend/dist/index.html"
  status = 200
