# Backend build setting
[build]
  command = "cd backend && npm run build"  # Vite build
  functions = "backend/functions"
  

# Frontend build setting
[build]
  command = "cd frontend && npm run build"  # Vite build
  publish = "frontend/dist"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
