##############################
# Netlify configuration file #
##############################

[build]
  # Backend build settings
  command = "cd backend && npm i && npm run build"  # Vite build
  functions = "backend/functions"

[[build]]
  command = "cd frontend && npm i && npm run build"  # Vite build
  publish = "frontend/dist"  

[[redirects]]
  from = "/*"
  to = "/frontend/dist/index.html"
  status = 200
