[build]
  functions = "backend/functions"
  command = "npm run build"  # Vite build
  publish = "frontend/dist"  # Adjust based on your build output directory


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
