# build setting
[build]
  # Backend build settings
  command = "cd backend && npm run build"  # Vite build
  functions = "backend/functions"

  # Frontend build settings
  environment = { NODE_VERSION = "6.14.15" }
  command = "cd frontend && npm run build"  # Vite build
  publish = "frontend/dist"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
