# Backend build setting
[build]
  command = "cd backend && npm run build"  # Vite build
  functions = "backend/functions"

# Frontend build settings
[build.environment]
  NODE_VERSION = "6.14.15"  # Node.js used for the frontend build


# Frontend build setting
[build]
  command = "cd frontend && npm run build"  # Vite build
  publish = "frontend/dist"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
