##############################
# Netlify configuration file #
##############################

[build]
  # Backend build settings
  command = "npm run build" 
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/functions/books.js"
  status = 200
