##############################
# Netlify configuration file #
##############################

[build]
  # Backend build settings
  command = "npm run build" 
  functions = "functions"

[dev]
 command =  "npm start"
 port = 3000

[[redirects]]
  from = "/*"
  to = "/backend/functions/books.js"
  status = 200
